### ISSUE TITLE
Issue with HEPGen from PCAP

### ISSUE THREAD

**Issue by idanacontaqt** [sipcapture/hepgen.js#18]
hey, i use this command per the syntax at readme

hepgen.js -s 127.0.0.1 -p 9063 -P "/root/sip.pcap"

this the output:
```

/usr/local/lib/node_modules/hepgen.js/hepgen.js:31
    socket.on('error', socketErrorHandler);
           ^

TypeError: Cannot read property 'on' of undefined
    at getSocket (/usr/local/lib/node_modules/hepgen.js/hepgen.js:31:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/hepgen.js/hepgen.js:223:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```
its the same if i use 9060 instead of 9063. The other json scenarios are working but not when i try to use pcap file with genuine sip traffic.

thank you

**Comment by lmangani** [comment]
> Custom from PCAP TEXT

Are you using a text format PCAP? Binary won't work.

**Comment by idanacontaqt** [comment]
ive tested with .pcap and converted it to text from Wireshark(export packet dissactions -> as plain text)
